env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react/recommended
  - plugin:react-hooks/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: true
  ecmaFeatures:
    jsx: true
plugins:
  - "@typescript-eslint"
  - "simple-import-sort"
  - react
  - react-hooks
rules:
  "sort-imports": "off"
  "simple-import-sort/imports": "error"
  "simple-import-sort/exports": "error"
  # Not needed in react v18:
  "react/react-in-jsx-scope": "off"
#  "import/first": "error",
#  "import/newline-after-import": "error",
#  "import/no-duplicates": "error"
settings:
  react:
    version: "detect"
