env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:cypress/recommended
  - plugin:chai-friendly/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: true
  ecmaFeatures:
    jsx: true
plugins:
  - "@typescript-eslint"
  - "simple-import-sort"
  - react
  - react-hooks
  - cypress
  - chai-friendly
rules:
  "sort-imports": "off"
  "simple-import-sort/imports": "error"
  "simple-import-sort/exports": "error"
  # Not needed in react v18:
  "react/react-in-jsx-scope": "off"
  #  "import/first": "error",
  #  "import/newline-after-import": "error",
  #  "import/no-duplicates": "error"
  "@typescript-eslint/no-unused-vars": "error"
  "cypress/assertion-before-screenshot": "error"
settings:
  react:
    version: "detect"
